server:
  port: 8989
spring:  application:    name: CLOUD-GATEWAY
    
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/order/**
#          filters:#          - name: CircuitBreaker
#            args:#             name: order-service-circuit-breaker
#             fallbackuri : forward:/orderFallBack
#           
        - id: payment-service
          uri: lb://PAYMENT-SERVICE1
          predicates:
            - Path=/api/payment/**
          filters:
          - name: CircuitBreaker
            args:
             name: payment-service-circuit-breaker
             fallbackuri : forward:/paymentFallBack
             
        - id: todo-order-service
          uri: lb://TODO-ORDER-SERVICE
          predicates:
            - Path=/api/todo/** #  cloud:#    gateway:#      routes:#      - id: order-service
#        uri: lb://ORDER-SERVICE
#        predicates:#          - Path=/order/**##            

     
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
     hostname: localhost
     
management:  endpoints:    web:      exposure:        include:        - hystrix.stream   

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000  
            

    